package utility;

public class Constant {

	public static String DB_PUBLIC_TRANSPORTATION = "db/Public Transportation.db3";
	public static String DB_URL_PUBLIC_TRANSPORTATION = "jdbc:sqlite:" + DB_PUBLIC_TRANSPORTATION;
	public static String DB_USERS = "db/Users.db3";
	public static String DB_URL_USERS = "jdbc:sqlite:" + DB_USERS;
	public static String[] URLS = { DB_URL_PUBLIC_TRANSPORTATION, DB_URL_USERS };
	public static String[] DBS = { DB_PUBLIC_TRANSPORTATION, DB_USERS };
	
	public static String pullman = "PULLMAN";
	public static String funicular = "FUNICULAR";
	public static String train = "TRAIN";
	public static String tram = "TRAM";
	public static String station = "STATION";
	public static String company = "COMPANY";
	public static String timetable = "TIMETABLE";
	public static String license_plate = "LICENSE PLATE";
	public static String id = "ID";
	public static String driver = "DRIVER";
	public static String state = "STATE";
	public static String number_of_seats = "NUMBER OF SEATS";
	public static String number_of_carriages = "NUMBER OF CARRIAGES";
	public static String address = "ADDRESS";
	public static String place = "PLACE";
	public static String time = "TIME";
	public static String departure_station = "DEPARTURE STATION";
	public static String arrival_station = "ARRIVAL STATION";
	public static String departure_timetable = "DEPARTURE TIMETABLE";
	public static String arrival_timetable = "ARRIVAL TIMETABLE";
	public static String description = "DESCRIPTION";
	public static String name = "NAME";
	public static String surname = "SURNAME";
	public static String fiscal_code = "FISCAL CODE";
	public static String place_of_birth = "PLACE OF BIRTH";
	public static String date_of_birth = "DATE OF BIRTH";
	public static String CAP = "CAP";
	public static String town = "TOWN";
	public static String province = "PROVINCE";
	public static String street_number = "STREET NUMBER";
	public static String legal_structure = "LEGAL STRUCTURE";
	public static String business_tax_code = "BUSINESS TAX CODE";
	public static String company_registration_number = "COMPANY REGISTRATION NUMBER";
	public static String incorporation_date = "INCORPORATION DATE";
	public static String legal_representative = "LEGAL REPRESENTATIVE";
	public static String number_of_employees = "NUMBER OF EMPLOYEES";
	public static String ATECO_code = "ATECO CODE";
	public static String telephone = "TELEPHONE";
	public static String mail = "MAIL";
	public static String social = "SOCIAL";
	public static String web_site = "WEB SITE";
	public static String stop = "STOP";
	public static String user = "USER";
	public static String registered_user = "REGISTERED USER";
	public static String manager = "MANAGER";
	public static String developer = "DEVELOPER";
	public static String password = "PASSWORD";
	public static String registered_office = "REGISTERED OFFICE";
}
